

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-budget
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budgeting_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-budget
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql

  php:
    build: .
    container_name: php-budget
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data: